// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbH0wsB6H8UDcQthiOsqdhKXZ5-QMGxE',
    appId: '1:879830721612:web:18c1c58b2cee2bb2d080e9',
    messagingSenderId: '879830721612',
    projectId: 'seekr-ai-ee45d',
    authDomain: 'seekr-ai-ee45d.firebaseapp.com',
    storageBucket: 'seekr-ai-ee45d.firebasestorage.app',
    measurementId: 'G-922M56GPSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEXDyAKysKxpUPIZNuvXT3hdxd-ZvZzlk',
    appId: '1:879830721612:android:a8aa9f5b4dfffd3cd080e9',
    messagingSenderId: '879830721612',
    projectId: 'seekr-ai-ee45d',
    storageBucket: 'seekr-ai-ee45d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2EibVb8HJ3TJXCkivLpZjLaLlY1QpsZs',
    appId: '1:879830721612:ios:672fd8dc7bb85242d080e9',
    messagingSenderId: '879830721612',
    projectId: 'seekr-ai-ee45d',
    storageBucket: 'seekr-ai-ee45d.firebasestorage.app',
    iosBundleId: 'com.example.seekrCheckpoint1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2EibVb8HJ3TJXCkivLpZjLaLlY1QpsZs',
    appId: '1:879830721612:ios:672fd8dc7bb85242d080e9',
    messagingSenderId: '879830721612',
    projectId: 'seekr-ai-ee45d',
    storageBucket: 'seekr-ai-ee45d.firebasestorage.app',
    iosBundleId: 'com.example.seekrCheckpoint1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHbH0wsB6H8UDcQthiOsqdhKXZ5-QMGxE',
    appId: '1:879830721612:web:ab99cdeeb52042a9d080e9',
    messagingSenderId: '879830721612',
    projectId: 'seekr-ai-ee45d',
    authDomain: 'seekr-ai-ee45d.firebaseapp.com',
    storageBucket: 'seekr-ai-ee45d.firebasestorage.app',
    measurementId: 'G-SDGQNVH5DV',
  );
}
